using System.Collections.Generic;
using Gx12.Launcher.Wpf.Models;

namespace Gx12.Launcher.Wpf.Services;

public static class ProfileSchema
{
    public static IReadOnlyList<ProfileSettingDefinition> Definitions { get; } = BuildDefinitions();

    private static IReadOnlyList<ProfileSettingDefinition> BuildDefinitions()
    {
        return new[]
        {
            D("trainer", "name", "Profile name", SettingKind.String, SettingTier.Basic, "Trainer", "Flight Basics", "\"unnamed\"", "Displayed profile name."),
            D("trainer", "port", "Trainer port", SettingKind.String, SettingTier.Advanced, "Trainer", "Settings Catalog", "\"auto\"", "Composite CDC port. Use auto for normal GX12 discovery."),
            D("trainer", "seconds", "Run duration", SettingKind.Integer, SettingTier.Advanced, "Trainer", "Settings Catalog", "0", "Trainer run duration; 0 means until stopped.", "0..3600"),
            D("trainer", "frame_rate_hz", "Frame rate", SettingKind.Integer, SettingTier.Basic, "Trainer", "Flight Basics", "1000", "Trainer frame rate sent to the GX12.", "1..8000"),
            D("trainer", "resolution_mode", "2x resolution", SettingKind.Enum, SettingTier.Experimental, "Trainer / Resolution", "Flight Basics", "\"legacy\"", "GX12 high-resolution trainer transport mode.", "", "legacy", "gx12_2x"),

            D("safety", "stop_key", "Stop key", SettingKind.String, SettingTier.Basic, "Safety", "Flight Basics", "\"Esc\"", "Global key that stops a managed run."),
            D("safety", "freeze_key", "Freeze key", SettingKind.String, SettingTier.Basic, "Safety", "Flight Basics", "\"F2\"", "Global key that freezes trainer output."),
            D("control", "mode", "Control mode", SettingKind.Enum, SettingTier.Basic, "Control", "Flight Basics", "\"direct_mouse\"", "Selects direct mouse or reticle aim control.", "", "direct_mouse", "drone_mouse_aim"),

            D("mapper", "roll_gain", "Roll gain", SettingKind.Number, SettingTier.Basic, "Right Stick / Core", "Right Stick Basic", "50.0", "Right-stick roll gain.", "0..5000"),
            D("mapper", "pitch_gain", "Pitch gain", SettingKind.Number, SettingTier.Basic, "Right Stick / Core", "Right Stick Basic", "50.0", "Right-stick pitch gain.", "0..5000"),
            D("mapper", "max_output", "Max output", SettingKind.Integer, SettingTier.Basic, "Right Stick / Core", "Right Stick Basic", "512", "Maximum trainer output for right-stick axes.", "1..512"),
            D("mapper", "deadband", "Deadband", SettingKind.Integer, SettingTier.Basic, "Right Stick / Core", "Right Stick Basic", "0", "Input deadband around neutral.", "0..512"),
            D("mapper", "output_curve", "Output curve", SettingKind.Enum, SettingTier.Advanced, "Right Stick / Shaping", "Settings Catalog", "\"expo\"", "Right-stick output curve mode.", "", "expo", "nodes", "actual"),
            D("mapper", "expo", "Expo", SettingKind.Number, SettingTier.Basic, "Right Stick / Core", "Right Stick Basic", "0.0", "Right-stick expo amount.", "0..0.95"),
            D("mapper", "smoothing", "Legacy smoothing", SettingKind.Number, SettingTier.Advanced, "Right Stick / Filter", "Settings Catalog", "0.0", "Legacy smoothing value. input_filter controls new filtering.", "0..1"),
            D("mapper", "input_filter", "Input filter", SettingKind.Enum, SettingTier.Advanced, "Right Stick / Filter", "Settings Catalog", "\"off\"", "Right-stick input filter.", "", "off", "smoothing", "one_euro"),
            D("mapper", "one_euro_min_cutoff_hz", "One Euro min cutoff", SettingKind.Number, SettingTier.Experimental, "Right Stick / Filter", "Settings Catalog", "1.0", "One Euro filter minimum cutoff.", ">0"),
            D("mapper", "one_euro_beta", "One Euro beta", SettingKind.Number, SettingTier.Experimental, "Right Stick / Filter", "Settings Catalog", "0.05", "One Euro filter speed response.", ">=0"),
            D("mapper", "one_euro_dcutoff_hz", "One Euro derivative cutoff", SettingKind.Number, SettingTier.Experimental, "Right Stick / Filter", "Settings Catalog", "1.0", "One Euro derivative cutoff.", ">0"),
            D("mapper", "despike_enabled", "Mouse despike", SettingKind.Boolean, SettingTier.Experimental, "Right Stick / Filter", "Settings Catalog", "false", "Hampel despike filter for right-stick mouse input."),
            D("mapper", "despike_count_enabled", "Count despikes", SettingKind.Boolean, SettingTier.Experimental, "Right Stick / Filter", "Settings Catalog", "false", "Report right-stick despike counts while running."),
            D("mapper", "despike_window", "Despike window", SettingKind.Integer, SettingTier.Experimental, "Right Stick / Filter", "Settings Catalog", "5", "Hampel despike sample window.", "odd 3..15"),
            D("mapper", "despike_threshold_sigma", "Despike threshold", SettingKind.Number, SettingTier.Experimental, "Right Stick / Filter", "Settings Catalog", "3.0", "Hampel despike threshold in sigma.", ">0"),

            D("mapper", "actual_center", "Actual center", SettingKind.Number, SettingTier.Experimental, "Right Stick / Actual Rates", "Settings Catalog", "0.45", "Actual Rates center response.", "0..1"),
            D("mapper", "actual_max", "Actual max", SettingKind.Number, SettingTier.Experimental, "Right Stick / Actual Rates", "Settings Catalog", "1.0", "Actual Rates maximum response.", "0..1"),
            D("mapper", "actual_expo", "Actual expo", SettingKind.Number, SettingTier.Experimental, "Right Stick / Actual Rates", "Settings Catalog", "0.30", "Actual Rates expo.", "0..0.95"),
            D("mapper", "position_model", "Position model", SettingKind.Enum, SettingTier.Experimental, "Right Stick / Dynamic Gimbal", "Settings Catalog", "\"integrator\"", "Right-stick virtual position model.", "", "integrator", "dynamic_gimbal"),
            D("mapper", "gimbal_frequency_hz", "Gimbal frequency", SettingKind.Number, SettingTier.Experimental, "Right Stick / Dynamic Gimbal", "Settings Catalog", "5.0", "Dynamic-gimbal natural frequency.", ">0"),
            D("mapper", "gimbal_damping_ratio", "Gimbal damping", SettingKind.Number, SettingTier.Experimental, "Right Stick / Dynamic Gimbal", "Settings Catalog", "1.15", "Dynamic-gimbal damping ratio.", ">=0"),
            D("mapper", "gimbal_input_impulse", "Gimbal impulse", SettingKind.Number, SettingTier.Experimental, "Right Stick / Dynamic Gimbal", "Settings Catalog", "1.0", "Dynamic-gimbal mouse impulse gain.", ">=0"),
            D("mapper", "gimbal_static_friction", "Static friction", SettingKind.Number, SettingTier.Experimental, "Right Stick / Dynamic Gimbal", "Settings Catalog", "0.0", "Dynamic-gimbal static friction.", ">=0"),
            D("mapper", "gimbal_dynamic_friction", "Dynamic friction", SettingKind.Number, SettingTier.Experimental, "Right Stick / Dynamic Gimbal", "Settings Catalog", "0.0", "Dynamic-gimbal dynamic friction.", ">=0"),
            D("mapper", "gimbal_edge_bumper", "Edge bumper", SettingKind.Number, SettingTier.Experimental, "Right Stick / Dynamic Gimbal", "Settings Catalog", "0.0", "Extra damping near virtual edge.", ">=0"),
            D("mapper", "gimbal_antiwindup_enabled", "Anti-windup", SettingKind.Boolean, SettingTier.Experimental, "Right Stick / Dynamic Gimbal", "Settings Catalog", "true", "Limit dynamic-gimbal windup near output edges."),
            D("mapper", "gimbal_antiwindup_start", "Anti-windup start", SettingKind.Number, SettingTier.Experimental, "Right Stick / Dynamic Gimbal", "Settings Catalog", "0.92", "Normalized point where anti-windup starts.", "0..1"),
            D("mapper", "gimbal_antiwindup_min_gain", "Anti-windup min gain", SettingKind.Number, SettingTier.Experimental, "Right Stick / Dynamic Gimbal", "Settings Catalog", "0.10", "Minimum input gain during anti-windup.", "0..1"),
            D("mapper", "input_gain_mode", "Input gain mode", SettingKind.Enum, SettingTier.Experimental, "Right Stick / Adaptive Gain", "Settings Catalog", "\"flat\"", "Right-stick input gain mode.", "", "flat", "adaptive"),
            D("mapper", "adaptive_slow_gain", "Adaptive slow gain", SettingKind.Number, SettingTier.Experimental, "Right Stick / Adaptive Gain", "Settings Catalog", "0.65", "Input gain at low mouse speeds.", ">0"),
            D("mapper", "adaptive_fast_gain", "Adaptive fast gain", SettingKind.Number, SettingTier.Experimental, "Right Stick / Adaptive Gain", "Settings Catalog", "1.60", "Input gain at high mouse speeds.", ">0"),
            D("mapper", "adaptive_speed_low", "Adaptive speed low", SettingKind.Number, SettingTier.Experimental, "Right Stick / Adaptive Gain", "Settings Catalog", "120.0", "Low speed threshold for adaptive gain.", ">=0"),
            D("mapper", "adaptive_speed_high", "Adaptive speed high", SettingKind.Number, SettingTier.Experimental, "Right Stick / Adaptive Gain", "Settings Catalog", "1800.0", "High speed threshold for adaptive gain.", ">=0"),
            D("mapper", "adaptive_curve", "Adaptive curve", SettingKind.Number, SettingTier.Experimental, "Right Stick / Adaptive Gain", "Settings Catalog", "1.0", "Adaptive gain blend curve.", ">0"),
            D("mapper", "adaptive_tracker_ms", "Tracker ms", SettingKind.Number, SettingTier.Experimental, "Right Stick / Adaptive Gain", "Settings Catalog", "35.0", "Speed tracker smoothing window.", ">=0"),
            D("mapper", "gate_shape", "Gate shape", SettingKind.Enum, SettingTier.Experimental, "Right Stick / Gates", "Settings Catalog", "\"axis\"", "Radial gate shape for right-stick output.", "", "axis", "circle", "octagon", "square"),
            D("mapper", "diagonal_scale", "Diagonal scale", SettingKind.Number, SettingTier.Experimental, "Right Stick / Gates", "Settings Catalog", "1.0", "Diagonal scale for radial gates.", ">0"),

            D("mapper", "return_enabled", "Idle return", SettingKind.Boolean, SettingTier.Basic, "Right Stick / Return", "Settings Catalog", "false", "Enable idle recentering."),
            D("mapper", "return_rate", "Idle return rate", SettingKind.Number, SettingTier.Basic, "Right Stick / Return", "Settings Catalog", "0", "Idle recentering rate.", ">=0"),
            D("mapper", "return_idle_ms", "Idle return delay", SettingKind.Number, SettingTier.Basic, "Right Stick / Return", "Settings Catalog", "0", "Idle time before return starts.", "0..1000"),
            D("mapper", "constant_return_enabled", "Constant return", SettingKind.Boolean, SettingTier.Basic, "Right Stick / Return", "Settings Catalog", "false", "Enable constant-rate recentering."),
            D("mapper", "constant_return_rate", "Constant return rate", SettingKind.Number, SettingTier.Basic, "Right Stick / Return", "Settings Catalog", "0", "Constant recentering rate.", ">=0"),
            D("mapper", "elastic_return_enabled", "Elastic return", SettingKind.Boolean, SettingTier.Basic, "Right Stick / Return", "Settings Catalog", "false", "Enable spring-like recentering."),
            D("mapper", "elastic_return_mode", "Elastic return mode", SettingKind.Enum, SettingTier.Basic, "Right Stick / Return", "Settings Catalog", "\"progressive\"", "Elastic return curve family.", "", "progressive", "linear", "smoothstep", "expo"),
            D("mapper", "elastic_return_coefficient", "Elastic coefficient", SettingKind.Number, SettingTier.Basic, "Right Stick / Return", "Settings Catalog", "0", "Spring coefficient in 1/s.", ">=0"),
            D("mapper", "elastic_return_curve", "Elastic curve", SettingKind.Number, SettingTier.Basic, "Right Stick / Return", "Settings Catalog", "0", "Elastic curve strength.", ">=0"),
            D("mapper", "output_shaping_enabled", "Output shaping", SettingKind.Boolean, SettingTier.Advanced, "Right Stick / Shaping", "Settings Catalog", "false", "Enable output shape nodes."),
            D("mapper", "output_shape_nodes", "Output shape nodes", SettingKind.Array, SettingTier.Advanced, "Right Stick / Shaping", "Settings Catalog", "[]", "Right-stick output shape nodes."),
            D("mapper", "return_shaping_enabled", "Return shaping", SettingKind.Boolean, SettingTier.Advanced, "Right Stick / Shaping", "Settings Catalog", "false", "Enable return shape nodes."),
            D("mapper", "return_shape_nodes", "Return shape nodes", SettingKind.Array, SettingTier.Advanced, "Right Stick / Shaping", "Settings Catalog", "[]", "Right-stick return shape nodes."),
            D("mapper", "invert_roll", "Invert roll", SettingKind.Boolean, SettingTier.Basic, "Right Stick / Axes", "Right Stick Basic", "false", "Invert right-stick roll output."),
            D("mapper", "invert_pitch", "Invert pitch", SettingKind.Boolean, SettingTier.Basic, "Right Stick / Axes", "Right Stick Basic", "false", "Invert right-stick pitch output."),
            D("mapper", "swap_axes", "Swap axes", SettingKind.Boolean, SettingTier.Basic, "Right Stick / Axes", "Right Stick Basic", "false", "Swap right-stick roll and pitch axes."),

            D("mouse_aim", "sensitivity_x", "Aim sensitivity X", SettingKind.Number, SettingTier.Basic, "Reticle Aim", "Reticle Aim Basic", "1.0", "Reticle-aim X sensitivity.", ">0"),
            D("mouse_aim", "sensitivity_y", "Aim sensitivity Y", SettingKind.Number, SettingTier.Basic, "Reticle Aim", "Reticle Aim Basic", "1.0", "Reticle-aim Y sensitivity.", ">0"),
            D("mouse_aim", "reticle_limit", "Reticle limit", SettingKind.Number, SettingTier.Basic, "Reticle Aim", "Reticle Aim Basic", "512", "Reticle-aim travel limit.", ">0"),
            D("mouse_aim", "reticle_deadband", "Reticle deadband", SettingKind.Number, SettingTier.Basic, "Reticle Aim", "Reticle Aim Basic", "8", "Reticle-aim deadband.", ">=0"),
            D("mouse_aim", "reticle_return_rate", "Reticle return", SettingKind.Number, SettingTier.Basic, "Reticle Aim", "Reticle Aim Basic", "0", "Reticle-aim return rate.", ">=0"),
            D("mouse_aim", "output_smoothing", "Aim smoothing", SettingKind.Number, SettingTier.Basic, "Reticle Aim", "Reticle Aim Basic", "0.10", "Reticle-aim output smoothing.", "0..1"),
            D("mouse_aim", "roll_gain", "Aim roll gain", SettingKind.Number, SettingTier.Basic, "Reticle Aim", "Reticle Aim Basic", "0.65", "Reticle-aim roll gain.", "0..5"),
            D("mouse_aim", "yaw_gain", "Aim yaw gain", SettingKind.Number, SettingTier.Basic, "Reticle Aim", "Reticle Aim Basic", "0.55", "Reticle-aim yaw gain.", "0..5"),
            D("mouse_aim", "pitch_gain", "Aim pitch gain", SettingKind.Number, SettingTier.Basic, "Reticle Aim", "Reticle Aim Basic", "0.85", "Reticle-aim pitch gain.", "0..5"),
            D("mouse_aim", "roll_max", "Aim roll max", SettingKind.Integer, SettingTier.Basic, "Reticle Aim", "Reticle Aim Basic", "420", "Reticle-aim roll maximum.", "0..512"),
            D("mouse_aim", "yaw_max", "Aim yaw max", SettingKind.Integer, SettingTier.Basic, "Reticle Aim", "Reticle Aim Basic", "360", "Reticle-aim yaw maximum.", "0..512"),
            D("mouse_aim", "pitch_max", "Aim pitch max", SettingKind.Integer, SettingTier.Basic, "Reticle Aim", "Reticle Aim Basic", "420", "Reticle-aim pitch maximum.", "0..512"),
            D("mouse_aim", "slew_rate", "Aim slew rate", SettingKind.Number, SettingTier.Basic, "Reticle Aim", "Reticle Aim Basic", "9000", "Reticle-aim output slew limit.", ">=0"),
            D("mouse_aim", "invert_x", "Aim invert X", SettingKind.Boolean, SettingTier.Basic, "Reticle Aim", "Reticle Aim Basic", "false", "Invert reticle-aim X input."),
            D("mouse_aim", "invert_y", "Aim invert Y", SettingKind.Boolean, SettingTier.Basic, "Reticle Aim", "Reticle Aim Basic", "false", "Invert reticle-aim Y input."),

            D("mouse_right_stick", "enabled", "Right mouse enabled", SettingKind.Boolean, SettingTier.Basic, "Devices", "Flight Basics", "true", "Enable GameInput mouse for right stick."),
            D("mouse_devices", "right", "Right mouse token", SettingKind.String, SettingTier.Advanced, "Devices", "Settings Catalog", "\"auto\"", "Right mouse GameInput device token."),
            D("mouse_devices", "left", "Left mouse token", SettingKind.String, SettingTier.Advanced, "Devices", "Settings Catalog", "\"\"", "Left mouse GameInput device token."),

            D("mouse_left_stick", "enabled", "Second mouse enabled", SettingKind.Boolean, SettingTier.Basic, "Left Stick / Second Mouse", "Left Stick Source", "false", "Enable second mouse left-stick source."),
            D("mouse_left_stick", "require_device", "Require left device", SettingKind.Boolean, SettingTier.Basic, "Left Stick / Second Mouse", "Left Stick Source", "true", "Require explicit second-mouse device."),
            D("mouse_left_stick", "throttle_rate", "Mouse throttle rate", SettingKind.Number, SettingTier.Basic, "Left Stick / Second Mouse", "Left Stick Source", "0.8", "Second-mouse throttle integration rate.", ">=0"),
            D("mouse_left_stick", "throttle_return_enabled", "Throttle return", SettingKind.Boolean, SettingTier.Advanced, "Left Stick / Second Mouse", "Settings Catalog", "false", "Enable second-mouse throttle return."),
            D("mouse_left_stick", "throttle_return_rate", "Throttle return rate", SettingKind.Number, SettingTier.Advanced, "Left Stick / Second Mouse", "Settings Catalog", "768.0", "Second-mouse throttle return rate.", ">=0"),
            D("mouse_left_stick", "yaw_gain", "Mouse yaw gain", SettingKind.Number, SettingTier.Basic, "Left Stick / Second Mouse", "Left Stick Source", "35.0", "Second-mouse yaw gain.", ">=0"),
            D("mouse_left_stick", "yaw_pulse", "Mouse yaw max", SettingKind.Integer, SettingTier.Basic, "Left Stick / Second Mouse", "Left Stick Source", "512", "Second-mouse yaw pulse maximum.", "0..512"),
            D("mouse_left_stick", "yaw_deadband", "Mouse yaw deadband", SettingKind.Integer, SettingTier.Basic, "Left Stick / Second Mouse", "Left Stick Source", "0", "Second-mouse yaw deadband.", "0..512"),
            D("mouse_left_stick", "yaw_smoothing", "Mouse yaw smoothing", SettingKind.Number, SettingTier.Advanced, "Left Stick / Yaw Shaping", "Settings Catalog", "0.0", "Legacy left-yaw smoothing.", "0..1"),
            D("mouse_left_stick", "yaw_slew_rate", "Mouse yaw slew", SettingKind.Number, SettingTier.Basic, "Left Stick / Second Mouse", "Left Stick Source", "0.0", "Second-mouse yaw slew limit.", ">=0"),
            D("mouse_left_stick", "yaw_shaping_enabled", "Yaw shaping", SettingKind.Boolean, SettingTier.Advanced, "Left Stick / Yaw Shaping", "Settings Catalog", "false", "Enable dedicated left-yaw shaping."),
            D("mouse_left_stick", "yaw_mapper_shaping_enabled", "Legacy yaw shaping alias", SettingKind.Boolean, SettingTier.Advanced, "Left Stick / Yaw Shaping", "Settings Catalog", "false", "Legacy alias for yaw shaping; retained for compatibility."),
            D("mouse_left_stick", "yaw_input_filter", "Yaw input filter", SettingKind.Enum, SettingTier.Advanced, "Left Stick / Yaw Shaping", "Settings Catalog", "\"off\"", "Left-yaw input filter.", "", "off", "smoothing", "one_euro"),
            D("mouse_left_stick", "yaw_one_euro_min_cutoff_hz", "Yaw One Euro min cutoff", SettingKind.Number, SettingTier.Experimental, "Left Stick / Yaw Filter", "Settings Catalog", "1.0", "Left-yaw One Euro minimum cutoff.", ">0"),
            D("mouse_left_stick", "yaw_one_euro_beta", "Yaw One Euro beta", SettingKind.Number, SettingTier.Experimental, "Left Stick / Yaw Filter", "Settings Catalog", "0.05", "Left-yaw One Euro beta.", ">=0"),
            D("mouse_left_stick", "yaw_one_euro_dcutoff_hz", "Yaw One Euro derivative cutoff", SettingKind.Number, SettingTier.Experimental, "Left Stick / Yaw Filter", "Settings Catalog", "1.0", "Left-yaw One Euro derivative cutoff.", ">0"),
            D("mouse_left_stick", "yaw_despike_enabled", "Yaw despike", SettingKind.Boolean, SettingTier.Experimental, "Left Stick / Yaw Filter", "Settings Catalog", "false", "Hampel despike filter for left yaw."),
            D("mouse_left_stick", "yaw_despike_count_enabled", "Count yaw despikes", SettingKind.Boolean, SettingTier.Experimental, "Left Stick / Yaw Filter", "Settings Catalog", "false", "Report left-yaw despike counts."),
            D("mouse_left_stick", "yaw_despike_window", "Yaw despike window", SettingKind.Integer, SettingTier.Experimental, "Left Stick / Yaw Filter", "Settings Catalog", "5", "Left-yaw despike window.", "odd 3..15"),
            D("mouse_left_stick", "yaw_despike_threshold_sigma", "Yaw despike threshold", SettingKind.Number, SettingTier.Experimental, "Left Stick / Yaw Filter", "Settings Catalog", "3.0", "Left-yaw despike sigma threshold.", ">0"),
            D("mouse_left_stick", "yaw_output_curve", "Yaw output curve", SettingKind.Enum, SettingTier.Advanced, "Left Stick / Yaw Shaping", "Settings Catalog", "\"expo\"", "Left-yaw output curve mode.", "", "expo", "nodes", "actual"),
            D("mouse_left_stick", "yaw_expo", "Yaw expo", SettingKind.Number, SettingTier.Advanced, "Left Stick / Yaw Shaping", "Settings Catalog", "0.0", "Left-yaw expo.", "0..0.95"),
            D("mouse_left_stick", "yaw_actual_center", "Yaw Actual center", SettingKind.Number, SettingTier.Experimental, "Left Stick / Yaw Actual Rates", "Settings Catalog", "0.45", "Left-yaw Actual Rates center response.", "0..1"),
            D("mouse_left_stick", "yaw_actual_max", "Yaw Actual max", SettingKind.Number, SettingTier.Experimental, "Left Stick / Yaw Actual Rates", "Settings Catalog", "1.0", "Left-yaw Actual Rates maximum response.", "0..1"),
            D("mouse_left_stick", "yaw_actual_expo", "Yaw Actual expo", SettingKind.Number, SettingTier.Experimental, "Left Stick / Yaw Actual Rates", "Settings Catalog", "0.30", "Left-yaw Actual Rates expo.", "0..0.95"),
            D("mouse_left_stick", "yaw_position_model", "Yaw position model", SettingKind.Enum, SettingTier.Experimental, "Left Stick / Yaw Dynamic Gimbal", "Settings Catalog", "\"integrator\"", "Left-yaw virtual position model.", "", "integrator", "dynamic_gimbal"),
            D("mouse_left_stick", "yaw_gimbal_frequency_hz", "Yaw gimbal frequency", SettingKind.Number, SettingTier.Experimental, "Left Stick / Yaw Dynamic Gimbal", "Settings Catalog", "5.0", "Left-yaw dynamic-gimbal frequency.", ">0"),
            D("mouse_left_stick", "yaw_gimbal_damping_ratio", "Yaw gimbal damping", SettingKind.Number, SettingTier.Experimental, "Left Stick / Yaw Dynamic Gimbal", "Settings Catalog", "1.15", "Left-yaw dynamic-gimbal damping.", ">=0"),
            D("mouse_left_stick", "yaw_gimbal_input_impulse", "Yaw gimbal impulse", SettingKind.Number, SettingTier.Experimental, "Left Stick / Yaw Dynamic Gimbal", "Settings Catalog", "1.0", "Left-yaw mouse impulse gain.", ">=0"),
            D("mouse_left_stick", "yaw_gimbal_static_friction", "Yaw static friction", SettingKind.Number, SettingTier.Experimental, "Left Stick / Yaw Dynamic Gimbal", "Settings Catalog", "0.0", "Left-yaw static friction.", ">=0"),
            D("mouse_left_stick", "yaw_gimbal_dynamic_friction", "Yaw dynamic friction", SettingKind.Number, SettingTier.Experimental, "Left Stick / Yaw Dynamic Gimbal", "Settings Catalog", "0.0", "Left-yaw dynamic friction.", ">=0"),
            D("mouse_left_stick", "yaw_gimbal_edge_bumper", "Yaw edge bumper", SettingKind.Number, SettingTier.Experimental, "Left Stick / Yaw Dynamic Gimbal", "Settings Catalog", "0.0", "Left-yaw edge damping.", ">=0"),
            D("mouse_left_stick", "yaw_gimbal_antiwindup_enabled", "Yaw anti-windup", SettingKind.Boolean, SettingTier.Experimental, "Left Stick / Yaw Dynamic Gimbal", "Settings Catalog", "true", "Limit left-yaw dynamic-gimbal windup."),
            D("mouse_left_stick", "yaw_gimbal_antiwindup_start", "Yaw anti-windup start", SettingKind.Number, SettingTier.Experimental, "Left Stick / Yaw Dynamic Gimbal", "Settings Catalog", "0.92", "Left-yaw anti-windup start.", "0..1"),
            D("mouse_left_stick", "yaw_gimbal_antiwindup_min_gain", "Yaw anti-windup min gain", SettingKind.Number, SettingTier.Experimental, "Left Stick / Yaw Dynamic Gimbal", "Settings Catalog", "0.10", "Left-yaw anti-windup minimum gain.", "0..1"),
            D("mouse_left_stick", "yaw_input_gain_mode", "Yaw input gain mode", SettingKind.Enum, SettingTier.Experimental, "Left Stick / Yaw Adaptive Gain", "Settings Catalog", "\"flat\"", "Left-yaw input gain mode.", "", "flat", "adaptive"),
            D("mouse_left_stick", "yaw_adaptive_slow_gain", "Yaw adaptive slow gain", SettingKind.Number, SettingTier.Experimental, "Left Stick / Yaw Adaptive Gain", "Settings Catalog", "0.65", "Left-yaw gain at low mouse speeds.", ">0"),
            D("mouse_left_stick", "yaw_adaptive_fast_gain", "Yaw adaptive fast gain", SettingKind.Number, SettingTier.Experimental, "Left Stick / Yaw Adaptive Gain", "Settings Catalog", "1.60", "Left-yaw gain at high mouse speeds.", ">0"),
            D("mouse_left_stick", "yaw_adaptive_speed_low", "Yaw adaptive speed low", SettingKind.Number, SettingTier.Experimental, "Left Stick / Yaw Adaptive Gain", "Settings Catalog", "120.0", "Left-yaw adaptive low speed threshold.", ">=0"),
            D("mouse_left_stick", "yaw_adaptive_speed_high", "Yaw adaptive speed high", SettingKind.Number, SettingTier.Experimental, "Left Stick / Yaw Adaptive Gain", "Settings Catalog", "1800.0", "Left-yaw adaptive high speed threshold.", ">=0"),
            D("mouse_left_stick", "yaw_adaptive_curve", "Yaw adaptive curve", SettingKind.Number, SettingTier.Experimental, "Left Stick / Yaw Adaptive Gain", "Settings Catalog", "1.0", "Left-yaw adaptive gain curve.", ">0"),
            D("mouse_left_stick", "yaw_adaptive_tracker_ms", "Yaw tracker ms", SettingKind.Number, SettingTier.Experimental, "Left Stick / Yaw Adaptive Gain", "Settings Catalog", "35.0", "Left-yaw speed tracker window.", ">=0"),
            D("mouse_left_stick", "yaw_gate_shape", "Yaw gate shape", SettingKind.Enum, SettingTier.Experimental, "Left Stick / Yaw Gates", "Settings Catalog", "\"axis\"", "Left-yaw gate shape.", "", "axis", "circle", "octagon", "square"),
            D("mouse_left_stick", "yaw_diagonal_scale", "Yaw diagonal scale", SettingKind.Number, SettingTier.Experimental, "Left Stick / Yaw Gates", "Settings Catalog", "1.0", "Left-yaw diagonal scale.", ">0"),
            D("mouse_left_stick", "yaw_return_enabled", "Yaw return", SettingKind.Boolean, SettingTier.Basic, "Left Stick / Yaw Return", "Settings Catalog", "false", "Enable left-yaw idle return."),
            D("mouse_left_stick", "yaw_return_rate", "Yaw return rate", SettingKind.Number, SettingTier.Basic, "Left Stick / Yaw Return", "Settings Catalog", "0", "Left-yaw idle return rate.", ">=0"),
            D("mouse_left_stick", "yaw_return_idle_ms", "Yaw return delay", SettingKind.Number, SettingTier.Basic, "Left Stick / Yaw Return", "Settings Catalog", "0", "Left-yaw idle return delay.", "0..1000"),
            D("mouse_left_stick", "yaw_constant_return_enabled", "Yaw constant return", SettingKind.Boolean, SettingTier.Basic, "Left Stick / Yaw Return", "Settings Catalog", "false", "Enable left-yaw constant return."),
            D("mouse_left_stick", "yaw_constant_return_rate", "Yaw constant return rate", SettingKind.Number, SettingTier.Basic, "Left Stick / Yaw Return", "Settings Catalog", "0", "Left-yaw constant return rate.", ">=0"),
            D("mouse_left_stick", "yaw_elastic_return_enabled", "Yaw elastic return", SettingKind.Boolean, SettingTier.Basic, "Left Stick / Yaw Return", "Settings Catalog", "false", "Enable left-yaw elastic return."),
            D("mouse_left_stick", "yaw_elastic_return_mode", "Yaw elastic return mode", SettingKind.Enum, SettingTier.Basic, "Left Stick / Yaw Return", "Settings Catalog", "\"progressive\"", "Left-yaw elastic return mode.", "", "progressive", "linear", "smoothstep", "expo"),
            D("mouse_left_stick", "yaw_elastic_return_coefficient", "Yaw elastic coefficient", SettingKind.Number, SettingTier.Basic, "Left Stick / Yaw Return", "Settings Catalog", "0", "Left-yaw elastic coefficient.", ">=0"),
            D("mouse_left_stick", "yaw_elastic_return_curve", "Yaw elastic curve", SettingKind.Number, SettingTier.Basic, "Left Stick / Yaw Return", "Settings Catalog", "0", "Left-yaw elastic curve.", ">=0"),
            D("mouse_left_stick", "yaw_output_shaping_enabled", "Yaw output shaping", SettingKind.Boolean, SettingTier.Advanced, "Left Stick / Yaw Shaping", "Settings Catalog", "false", "Enable left-yaw output shape nodes."),
            D("mouse_left_stick", "yaw_return_shaping_enabled", "Yaw return shaping", SettingKind.Boolean, SettingTier.Advanced, "Left Stick / Yaw Shaping", "Settings Catalog", "false", "Enable left-yaw return shape nodes."),
            D("mouse_left_stick", "yaw_output_shape_nodes", "Yaw output shape nodes", SettingKind.Array, SettingTier.Advanced, "Left Stick / Yaw Shaping", "Settings Catalog", "[]", "Left-yaw output shape nodes."),
            D("mouse_left_stick", "yaw_return_shape_nodes", "Yaw return shape nodes", SettingKind.Array, SettingTier.Advanced, "Left Stick / Yaw Shaping", "Settings Catalog", "[]", "Left-yaw return shape nodes."),
            D("mouse_left_stick", "invert_throttle", "Invert throttle", SettingKind.Boolean, SettingTier.Basic, "Left Stick / Second Mouse", "Left Stick Source", "false", "Invert second-mouse throttle axis."),
            D("mouse_left_stick", "invert_yaw", "Invert mouse yaw", SettingKind.Boolean, SettingTier.Basic, "Left Stick / Second Mouse", "Left Stick Source", "false", "Invert second-mouse yaw axis."),
            D("mouse_left_stick", "swap_axes", "Swap left axes", SettingKind.Boolean, SettingTier.Basic, "Left Stick / Second Mouse", "Left Stick Source", "false", "Swap second-mouse throttle and yaw axes."),

            D("right_mouse_left_stick", "enabled", "Right mouse buttons/scroll enabled", SettingKind.Boolean, SettingTier.Basic, "Left Stick / Right Mouse Buttons", "Left Stick Source", "false", "Use right mouse Mouse4/Mouse5 plus wheel as the left-stick source."),
            D("right_mouse_left_stick", "throttle_step", "Scroll throttle step", SettingKind.Number, SettingTier.Basic, "Left Stick / Right Mouse Buttons", "Left Stick Source", "64.0", "Throttle units per wheel notch when scroll controls throttle.", "0..1024"),
            D("right_mouse_left_stick", "throttle_button_rate", "Button throttle rate", SettingKind.Number, SettingTier.Basic, "Left Stick / Right Mouse Buttons", "Left Stick Source", "4096.0", "Throttle units per second when Mouse4/Mouse5 control throttle.", "0..10000"),
            D("right_mouse_left_stick", "throttle_return_enabled", "Button/scroll throttle return", SettingKind.Boolean, SettingTier.Basic, "Left Stick / Right Mouse Buttons", "Left Stick Source", "false", "Return throttle toward low when the selected throttle input is idle."),
            D("right_mouse_left_stick", "throttle_return_rate", "Button/scroll throttle return rate", SettingKind.Number, SettingTier.Basic, "Left Stick / Right Mouse Buttons", "Left Stick Source", "0.0", "Right-mouse button/scroll throttle return rate.", "0..20000"),
            D("right_mouse_left_stick", "yaw_pulse", "Button/scroll yaw max", SettingKind.Integer, SettingTier.Basic, "Left Stick / Right Mouse Buttons", "Left Stick Source", "512", "Maximum yaw output for the right-mouse button/scroll source.", "0..512"),
            D("right_mouse_left_stick", "yaw_scroll_step", "Scroll yaw step", SettingKind.Number, SettingTier.Basic, "Left Stick / Right Mouse Buttons", "Left Stick Source", "64.0", "Yaw units per wheel notch when scroll controls yaw.", "0..1024"),
            D("right_mouse_left_stick", "yaw_slew_rate", "Button/scroll yaw slew", SettingKind.Number, SettingTier.Basic, "Left Stick / Right Mouse Buttons", "Left Stick Source", "4096.0", "Yaw slew limit for the right-mouse button/scroll source.", "0..20000"),
            D("right_mouse_left_stick", "invert_throttle", "Invert button/scroll throttle", SettingKind.Boolean, SettingTier.Basic, "Left Stick / Right Mouse Buttons", "Left Stick Source", "false", "Invert throttle direction for the right-mouse button/scroll source."),
            D("right_mouse_left_stick", "invert_yaw", "Invert button/scroll yaw", SettingKind.Boolean, SettingTier.Basic, "Left Stick / Right Mouse Buttons", "Left Stick Source", "false", "Invert yaw direction for the right-mouse button/scroll source."),
            D("right_mouse_left_stick", "swap_axes", "Swap buttons/scroll", SettingKind.Boolean, SettingTier.Basic, "Left Stick / Right Mouse Buttons", "Left Stick Source", "false", "Swap so Mouse4/Mouse5 control throttle and scroll controls yaw."),

            D("keyboard_left_stick", "enabled", "Keyboard left enabled", SettingKind.Boolean, SettingTier.Basic, "Left Stick / Keyboard", "Left Stick Source", "false", "Enable keyboard or Wooting left-stick source."),
            D("keyboard_left_stick", "input_source", "Keyboard input source", SettingKind.Enum, SettingTier.Basic, "Left Stick / Keyboard", "Left Stick Source", "\"gameinput\"", "Keyboard left-stick input source.", "", "gameinput", "wooting_analog", "auto"),
            D("keyboard_left_stick", "require_analog", "Require analog", SettingKind.Boolean, SettingTier.Basic, "Left Stick / Keyboard", "Left Stick Source", "false", "Require analog values for Wooting source."),
            D("keyboard_left_stick", "block_selected_keys", "Block selected keys", SettingKind.Boolean, SettingTier.Advanced, "Left Stick / Keyboard", "Settings Catalog", "false", "Block chosen keyboard keys from other apps while running."),
            D("keyboard_left_stick", "throttle_up_key", "Throttle up key", SettingKind.String, SettingTier.Basic, "Left Stick / Keyboard", "Settings Catalog", "\"W\"", "Keyboard throttle-up key."),
            D("keyboard_left_stick", "throttle_down_key", "Throttle down key", SettingKind.String, SettingTier.Basic, "Left Stick / Keyboard", "Settings Catalog", "\"S\"", "Keyboard throttle-down key."),
            D("keyboard_left_stick", "throttle_cut_key", "Throttle cut key", SettingKind.String, SettingTier.Basic, "Left Stick / Keyboard", "Settings Catalog", "\"Space\"", "Keyboard throttle-cut key."),
            D("keyboard_left_stick", "throttle_rate", "Keyboard throttle rate", SettingKind.Number, SettingTier.Basic, "Left Stick / Keyboard", "Settings Catalog", "4096.0", "Keyboard throttle integration rate.", ">=0"),
            D("keyboard_left_stick", "throttle_return_enabled", "Keyboard throttle return", SettingKind.Boolean, SettingTier.Advanced, "Left Stick / Keyboard", "Settings Catalog", "false", "Enable keyboard throttle return."),
            D("keyboard_left_stick", "throttle_return_rate", "Keyboard throttle return rate", SettingKind.Number, SettingTier.Advanced, "Left Stick / Keyboard", "Settings Catalog", "0.0", "Keyboard throttle return rate.", ">=0"),
            D("keyboard_left_stick", "yaw_left_key", "Yaw left key", SettingKind.String, SettingTier.Basic, "Left Stick / Keyboard", "Settings Catalog", "\"A\"", "Keyboard yaw-left key."),
            D("keyboard_left_stick", "yaw_right_key", "Yaw right key", SettingKind.String, SettingTier.Basic, "Left Stick / Keyboard", "Settings Catalog", "\"D\"", "Keyboard yaw-right key."),
            D("keyboard_left_stick", "yaw_pulse", "Keyboard yaw max", SettingKind.Integer, SettingTier.Basic, "Left Stick / Keyboard", "Settings Catalog", "512", "Keyboard yaw pulse maximum.", "0..512"),
            D("keyboard_left_stick", "yaw_slew_rate", "Keyboard yaw slew", SettingKind.Number, SettingTier.Basic, "Left Stick / Keyboard", "Settings Catalog", "4096.0", "Keyboard yaw slew limit.", ">=0"),
            D("keyboard_left_stick", "invert_yaw", "Invert keyboard yaw", SettingKind.Boolean, SettingTier.Basic, "Left Stick / Keyboard", "Settings Catalog", "false", "Invert keyboard yaw direction."),
            D("keyboard_left_stick", "analog_keycode_mode", "Analog keycode mode", SettingKind.String, SettingTier.Advanced, "Left Stick / Wooting", "Settings Catalog", "\"virtual_key_translate\"", "Wooting analog keycode mode."),
            D("keyboard_left_stick", "analog_deadzone", "Analog deadzone", SettingKind.Number, SettingTier.Advanced, "Left Stick / Wooting", "Settings Catalog", "0.04", "Wooting analog deadzone.", "0..1"),
            D("keyboard_left_stick", "analog_curve", "Analog curve", SettingKind.Number, SettingTier.Advanced, "Left Stick / Wooting", "Settings Catalog", "1.0", "Wooting analog curve.", ">0"),
            D("keyboard_left_stick", "analog_min", "Analog min", SettingKind.Number, SettingTier.Advanced, "Left Stick / Wooting", "Settings Catalog", "0.0", "Minimum Wooting analog value.", "0..1"),
            D("keyboard_left_stick", "analog_max", "Analog max", SettingKind.Number, SettingTier.Advanced, "Left Stick / Wooting", "Settings Catalog", "1.0", "Maximum Wooting analog value.", "0..1"),

            D("logging", "csv", "CSV logging", SettingKind.Boolean, SettingTier.Advanced, "Logging", "Settings Catalog", "false", "Enable CSV logging."),
            D("logging", "path", "CSV log path", SettingKind.String, SettingTier.Advanced, "Logging", "Settings Catalog", "\"logs\\\\trainer-profile.csv\"", "CSV log output path."),
            D("logging", "every_n_frames", "CSV frame interval", SettingKind.Integer, SettingTier.Advanced, "Logging", "Settings Catalog", "1", "Write one CSV row every N frames.", ">=1")
        };
    }

    private static ProfileSettingDefinition D(
        string section,
        string key,
        string label,
        SettingKind kind,
        SettingTier tier,
        string group,
        string page,
        string defaultRawValue,
        string help,
        string rangeText = "",
        params string[] allowedValues)
    {
        var id = $"{section}.{key}";
        return new ProfileSettingDefinition(
            id,
            section,
            key,
            label,
            kind,
            tier,
            group,
            page,
            defaultRawValue,
            help,
            rangeText,
            allowedValues);
    }
}
